---
title: "GPCorrPlot"
author: "Kevin Bird"
date: "February 14, 2018"
output: html_document
---

```{r}
PredList <- list.files(path="C:\\Users/Kevin/Documents/At-GenomicSelection-Ruthie/GenicGeno/",
    pattern="*PRED.csv")

for(i in PredList){
    filepath <- file.path("C:\\Users/Kevin/Documents/At-GenomicSelection-Ruthie/GenicGeno/",paste(i))
    assign(i, read.delim(filepath,
    sep = ","))
}
#label by AA
GAPIT..ala.PRED.csv$AA<-"Ala"   
GAPIT..arg.PRED.csv$AA<-"Arg"
GAPIT..asp.PRED.csv$AA<-"Asp"
GAPIT..gln.PRED.csv$AA<-"Gln" 
GAPIT..glu.PRED.csv$AA<-"Glu"
GAPIT..Gly.PRED.csv$AA<-"Gly"
GAPIT..his.PRED.csv$AA<-"His"
GAPIT..ile.PRED.csv$AA<-"Ile"
GAPIT..leu.PRED.csv$AA<-"Leu"
GAPIT..lys.PRED.csv$AA<-"Lys"
GAPIT..met.PRED.csv$AA<-"Met"
GAPIT..phe.PRED.csv$AA<-"Phe"
GAPIT..pro.PRED.csv$AA<-"Pro"
GAPIT..ser.PRED.csv$AA<-"Ser"
GAPIT..thr.PRED.csv$AA<-"Thr"
GAPIT..Total.PRED.csv$AA<-"TFAA"
GAPIT..trp.PRED.csv$AA<-"Trp" 
GAPIT..try.PRED.csv$AA<-"Tyr"   
GAPIT..val.PRED.csv$AA<-"Val"

#join to observed phenotypes
AlaPred<-full_join(GAPIT..ala.PRED.csv,AAabs[,c(1,2)],by="Taxa")
ArgPred<-full_join(GAPIT..arg.PRED.csv,AAabs[,c(1,3)],by="Taxa")
AspPred<-full_join(GAPIT..asp.PRED.csv,AAabs[,c(1,4)],by="Taxa")
GlnPred<-full_join(GAPIT..gln.PRED.csv,AAabs[,c(1,5)],by="Taxa")
GluPred<-full_join(GAPIT..glu.PRED.csv,AAabs[,c(1,6)],by="Taxa")
GlyPred<-full_join(GAPIT..Gly.PRED.csv,AAabs[,c(1,7)],by="Taxa")
HisPred<-full_join(GAPIT..his.PRED.csv,AAabs[,c(1,8)],by="Taxa")
IlePred<-full_join(GAPIT..ile.PRED.csv,AAabs[,c(1,9)],by="Taxa")
LeuPred<-full_join(GAPIT..leu.PRED.csv,AAabs[,c(1,10)],by="Taxa")
LysPred<-full_join(GAPIT..lys.PRED.csv,AAabs[,c(1,11)],by="Taxa")
MetPred<-full_join(GAPIT..met.PRED.csv,AAabs[,c(1,12)],by="Taxa")
PhePred<-full_join(GAPIT..phe.PRED.csv,AAabs[,c(1,13)],by="Taxa")
ProPred<-full_join(GAPIT..pro.PRED.csv,AAabs[,c(1,14)],by="Taxa")
SerPred<-full_join(GAPIT..ser.PRED.csv,AAabs[,c(1,15)],by="Taxa")
ThrPred<-full_join(GAPIT..thr.PRED.csv,AAabs[,c(1,16)],by="Taxa")
TrpPred<-full_join(GAPIT..trp.PRED.csv,AAabs[,c(1,17)],by="Taxa")
TryPred<-full_join(GAPIT..try.PRED.csv,AAabs[,c(1,18)],by="Taxa")
ValPred<-full_join(GAPIT..val.PRED.csv,AAabs[,c(1,19)],by="Taxa")
TotalPred<-full_join(GAPIT..Total.PRED.csv,AAabs[,c(1,20)],by="Taxa")

```

```{r}
ChangeNames <- function(x) {
    names(x) <- c("Taxa","Group","RefInf","ID", "BLUP","PEV","BLUE","Prediction", "AA","Observed")
    return(x)
}
dfs<-list(AlaPred,ArgPred,AspPred,GlnPred,GluPred,GlyPred,HisPred,IlePred,LeuPred,LysPred,MetPred,PhePred,ProPred,SerPred,ThrPred,TrpPred,TryPred,ValPred,TotalPred)

dfs<-lapply(dfs,ChangeNames)

#rbind
AllPred <- do.call("rbind", dfs)



AllPred<-AllPred[which(AllPred$RefInf==2),]

```

```{r}
CorrPlot<-ggplot(AllPred,aes(x=Prediction,y=Observed))+geom_point()+geom_smooth(method="lm")+labs(xlab="Prediction (Testing)",ylab="Observed Phenotype")+facet_wrap(~AA,nrow=5,ncol=4,scales="free")+ background_grid(major = "xy", minor = "none")

ggsave('GPCorr.png',plot=CorrPlot,width = 35,height=25,units="cm")
```